spring:
  application:
    name: spring_security
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
